### ISSUE TITLE
Search Foods Functionality

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#10]
App của mình đã hoàn thiện xong những chức năng cơ bản. Giờ t định thêm chức năng search food 
trong phần list food mình đã làm.
Mọi người cho ý tưởng làm phần này nhé

**Comment by mrbillyco99** [comment]
Phần này chỉ có các thao tác đơn giản với database bằng câu lệnh sql, không phức tạp lắm. T sẽ làm phần này nhé

**Comment by kieth1205** [comment]
@mrbillyco99 code ok rồi nhé
