### ISSUE TITLE
Check internet connection

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#11]
Phần này t muốn thêm tính năng kiểm tra mạng từ thiết bị người dùng, nếu thiết bị không kết nối mạng sẽ hiện thông báo check lại kết nối mạng. 
Phần này cũng không có gì phải bàn nhiều nên mình giao @itula làm phần này nhé. Lúc làm có gì bị lỗi thì comment ở issues nhé, trên mạng phần check internet này hướng dẫn nhiều nên search tham khảo nhé.

**Comment by itula** [comment]
ok.t đang thực hiện r nha.

**Comment by kieth1205** [comment]
code chạy ok rồi nhé @itula
