### ISSUE TITLE
rating and adding favorite food

### ISSUE THREAD

**Issue by kieth1205** [Nguyenthinh19/SE03-Group19#13]
vì là ứng dụng order đồ ăn nên mình nghĩ chức năng đánh giá sao và thêm vào mục yêu thích sẽ khá là hợp lý. Mọi người thấy sao? Nếu ổn thì mình nhận code phần này.

**Comment by Nguyenthinh19** [comment]
t thấy thêm phần này cũng được . M muốn thêm phần này thì ok thôi.

**Comment by kieth1205** [comment]
ok. Vậy chốt nhé

**Comment by kieth1205** [comment]
@itula layout t làm xong rồi, m code tiếp nhé. Do DB t thực hiện chính nên t làm tiếp phần Delete Cart cho nhanh.

**Comment by itula** [comment]
ok nha.t đang thực hiện nó rồi
