### ISSUE TITLE
Bug on Search Function

### ISSUE THREAD

**Issue by kieth1205** [Nguyenthinh19/SE03-Group19#14]
tính năng tìm kiếm hoạt động không như mong đợi ở điểm:
- Khi ta chưa tìm kiếm thì trong gợi ý tìm kiếm sẽ trống, nhưng trong code không làm được vậy.

**Comment by Nguyenthinh19** [comment]
@mrbillyco99 code m bị lỗi rồi thì phải. Ko hiện lên đc list food?

**Comment by mrbillyco99** [comment]
Ok để t kiểm tra lại, fix xong t sẽ push code.

**Comment by kieth1205** [comment]
@mrbillyco99 code đã chạy ok rồi nhé
