### ISSUE TITLE
Delete Cart's item

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#15]
Ở phần làm về Order  ,  app mình còn thiếu chức năng xóa đi item food đã đặt trong Menu Cart. Trước phần Order do @kieth1205 Thắng làm, nên chức năng xóa này @kieth1205 thêm vào nhé.

**Comment by kieth1205** [comment]
@Nguyenthinh19 ok. Vậy để t làm phần này

**Comment by kieth1205** [comment]
Ok
