### ISSUE TITLE
Update Cart's Item

### ISSUE THREAD

**Issue by kieth1205** [Nguyenthinh19/SE03-Group19#16]
Do đang thực hiện với Cart nên t sẽ làm luôn về update cart luôn (tăng giảm số item trong Cart)

**Comment by Nguyenthinh19** [comment]
T thấy phần cart trước vẫn còn lỗi đấy. Khi mà click đặt một món ăn nhiều lần sẽ hiện lên nhiều đơn hàng của món ăn đấy. Như vậy không ổn. Fix lại chỗ đấy nhé. 
Với cả layout trong menu cart thì t muốn thêm cả ảnh món ăn vào trong từng cardview.

**Comment by kieth1205** [comment]
@Nguyenthinh19 ok. T sẽ thêm arnh món ăn vào trong đơn hàng luôn

**Comment by kieth1205** [comment]
Đã xong
