### ISSUE TITLE
Bug on rating funtionality

### ISSUE THREAD

**Issue by kieth1205** [Nguyenthinh19/SE03-Group19#18]
hiện tại theo t thấy thì app sẽ bị crash khi cùng 1 tài khoản thực hiện việc đánh giá nhiều hơn 1 món ăn

**Comment by kieth1205** [comment]
và giá trị trung bình của sao cũng không được tính

**Comment by itula** [comment]
ok.để t check lại xem.lúc code xong t test vẫn còn ổn áp

**Comment by Nguyenthinh19** [comment]
@itula 
- Phần giá trị trung bình m quên chưa gọi lại hàm getRatingFood() nên nó không hiện đánh giá sao.  Nhưng khi đánh giá 2 món ăn liên tiếp vẫn sẽ bị crash app, phần này m fix tiếp nhé.
- Phần Add Favorite m làm cũng bị lỗi là khi m click nút thả tim cho món ăn ưu thích, khi log out ra và login bằng tài khoản khác thì nút thả tim không được resert lại. Phần này sửa qua trên DB nên fix rồi.

**Comment by kieth1205** [comment]
Đã fix xong rồi nhé
