### ISSUE TITLE
Change item on Cart

### ISSUE THREAD

**Issue by kieth1205** [Nguyenthinh19/SE03-Group19#19]
Để tránh việc muốn mua thêm sản phẩm lại phải vào list để đặt thêm sản phẩm, hay việc giảm số lượng sản phẩm trong giỏ hàng thông qua việc xoá rồi đặt lại thì t sẽ thêm nút tăng giảm số lượng vào ngay trong giỏ hàng, thông qua đó người mua có thể tăng giảm số lượng sản phẩm trực tiếp ngay trong giỏ hàng luôn. Mọi người thấy sao?

**Comment by Nguyenthinh19** [comment]
uhm, thấy hợp lý thì làm thôi.
