### ISSUE TITLE
Công nghệ sử dụng

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#2]
Như đã thống nhất thì ta sẽ làm App Order Food, sử dụng Java Android. Vậy nên mọi người cần tải Android Studio (  Đây là một IDE cho nền tảng Android , giống như ta dùng Eclipse để code java, c,....) để có thể xây dựng App.

**Comment by kieth1205** [comment]
- Theo mình tìm hiểu thì nên dùng IDE là Android Studio cho tiện. Nó vừa cung cấp môi trường để code và máy ảo để chạy app demo luôn.
- Còn nếu máy ai cấu hình yếu thì có thể dùng Visual Studio Code, mã nguồn mở và khá nhẹ. Còn máy ảo thì có thể dùng Genimotion

**Comment by Nguyenthinh19** [comment]
@itula , @mrbillyco99  trong quá trình tải có vấn đề xảy ra có thể hỏi t hoặc @kieth1205  nhé

**Comment by itula** [comment]
t đang tải android studio 3.5.1.kb có phải bản mới nhất chưa

**Comment by Nguyenthinh19** [comment]
Cứ tải đi, ko sao đâu

**Comment by Nguyenthinh19** [comment]
Chủ yếu vẫn là ổ cứng SSD và Ram từ 8 trở lên, nếu có thì chạy đc

**Comment by mrbillyco99** [comment]
Bạn có thể cho mình xin tài liệu về Firebase được không? Mình chưa sử dụng qua nên chưa rõ lắm

**Comment by itula** [comment]
gg b ơi.k thi ib minh 50k :))

**Comment by itula** [comment]
t có nghe qua về fiirebase.n chưa sử dụng nhiều lắm

**Comment by Nguyenthinh19** [comment]
trong nhóm có mình và Thắng @kieth1205  từng sử dụng với Firebase làm nơi lưu trữ dữ liệu nên có thể control được vấn đề này. Vì Thành @mrbillyco99  và Trung @itula  chưa sử dụng qua nên việc đầu tiên ta sẽ làm là Tìm hiểu về Firebase.

**Comment by Nguyenthinh19** [comment]
Vậy quyết định là sử dụng Firebase nhé
