### ISSUE TITLE
Integrated Payment

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#21]
T muốn thêm chức năng thanh toán cho App, vì đây là chức năng khá quan trọng trong app order. 
Ở menu card, sau khi nhập order places thì sẽ chuyển đến màn hình thanh toán. Sau khi thanh toán xong dữ liệu mới chuyển lên database. 
- https://developer.paypal.com 
Link trên có hướng dẫn tích hợp phương thức thanh toán qua paypal vào app android.(bản test thôi)

mọi người cho thêm ý kiến làm phần này nhé. 
Phần này @mrbillyco99 Thành làm nhé, mọi người cx đang code phần khác. Chức năng này phải tích hợp 1 số thứ như t nhắn ở trên nên làm có gì vướng thì nhắn t support cho.

**Comment by mrbillyco99** [comment]
ok nhé

**Comment by kieth1205** [comment]
nay mới test được code. Chạy ok rồi nhé @mrbillyco99
