### ISSUE TITLE
Favorite Food List

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#23]
Phần xử lý sự kiện Add favorites food ok rồi, giờ t muốn thêm phần tạo danh sách list các món ăn ưu thích. Giao diện list favorite cũng sẽ giống giao diện list food thôi. 
@itula Trung làm tiếp phần này nhé. Có gì lỗi t support cho.

**Comment by itula** [comment]
ok man.t đang thực hiện nó rồi.
