### ISSUE TITLE
Cash on Delivery

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#25]
- Ở mục thanh toán, app mình sử dụng Paypal để thanh toán online, Thì t muốn thêm một phương thức thanh toán nữa là Cash on Delivery(trả tiền khi nhận hàng).
- Ở dialog điền thông tin địa chỉ , thì tạo thêm nội dung các phương thức thanh toán, sẽ có 2 sự lựa chọn gồm có paypal và cash on Delivery. Khi click vào paypal vẫn như app hiện tại. Khi click vào cash on Delivery thì update thông tin đơn hàng lên databse.

@mrbillyco99  m làm phần Paypal rồi thì làm tiếp phần cash on delivery nhé.
Có ý kiến gì comment bên dưới nhé

**Comment by mrbillyco99** [comment]
ok
