### ISSUE TITLE
Register, LogIn and Welcome

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#4]
Giao diện Welcome sẽ có 2 nút SignIn, và SignUp. Khi ấn vào nút SignUp sẽ hiện lên cửa sổ màn hình mới, trong đó người dùng sẽ điền thông tin Gồm Tên, Sdt, và password. 
3 thông tin trên sẽ được lưu vào FirebaseDatabase .

Mọi người cho ý kiến

**Comment by kieth1205** [comment]
Có nên cho phép đăng nhập với các tài khoản mạng xã hội không?

**Comment by kieth1205** [comment]
Điều hướng đối với đăng ký. Khi đã đưng ký thành công sẽ tự động chuyển về trang đăng nhập. Đăng nhậ p thành công thì chuyển qua giao diện chính của app

**Comment by Nguyenthinh19** [comment]
cứ đăng nhập theo tên, số điện thoại và password là đc rồi. Ko cần liên kết với bên ngoài.

**Comment by kieth1205** [comment]
@Nguyenthinh19 có dùng firebase auth không?

**Comment by Nguyenthinh19** [comment]
Ko
