### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#6]
Sau khi User đăng nhập thành công vào App, User sẽ vào màn hình menu. 
Ở đây ta sẽ bàn về màn hình Menu

**Comment by Nguyenthinh19** [comment]
Theo t nghĩ 
- Màn hình Menu sẽ hiện thị list các món ăn VD: Như fish,chicken, bergur, soup,....
- Dữ liệu về món ăn ta sẽ thêm trực tiếp trên Firebase Database. Mỗi món ăn được lưu trên Databse gồm Name và Image. 
- Ta sẽ lấy dữ liệu trên Firebase để hiện thị các món ăn lên trên App.

Mọi người suy nghĩ rồi cho ý kiến nhé.

**Comment by kieth1205** [comment]
đó là giao diện chính hả?

**Comment by Nguyenthinh19** [comment]
Đúng rồi

**Comment by itula** [comment]
t nghĩ phần các chữ nên cho to lên và chỉnh màu khác để nhìn cho rõ hơn 1 tẹo

**Comment by Nguyenthinh19** [comment]
phần chữ nào ?

**Comment by itula** [comment]
sau khi click vào đăng kí hoặc đăng nhập ý.mấy cái option để nhập ý

**Comment by Nguyenthinh19** [comment]
uhm cái đấy ở phần login mà. cái đấy sửa cx dc

**Comment by mrbillyco99** [comment]
theo t ngoài list món ăn nên có thêm các lựa chọn về giỏ hàng hay thông tin tài khoản của khách hàng ở trong menu

**Comment by mrbillyco99** [comment]
ngoài ra cũng nên có mục report để khách hàng có thể góp ý cho nhà hàng cũng như ứng dụng để cải thiện trong quá trình sử dụng

**Comment by Nguyenthinh19** [comment]
@mrbillyco99 ok, t sẽ thêm vào

**Comment by Nguyenthinh19** [comment]
phần này t vs @kieth1205 sẽ code phần này
