### ISSUE TITLE
Show details of food

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#7]
Sau khi người dùng chọn món ăn trong menu, chúng ta sẽ tạo một màn hình hiển thị toàn bộ thông tin chi tiết về món ăn bao gồm :
- Ảnh món ăn
- Tên món ăn
- Giá tiền
- Số lượng đặt hàng
- Mô tả về món ăn
- Nút đặt hàng

Mọi người cho ý kiến giao diện mình sẽ làm như như nào ?

**Comment by itula** [comment]
đầu tiên là danh sách món ăn có tên, hình ảnh và giá tiền.khi click và ảnh thì thêm chi tiết mô tả món ăn và nút đặt.t nghĩ thế mn thấy ssao

**Comment by mrbillyco99** [comment]
Vì ở giao diện menu chính đã cho hiển thị các nhóm món ăn nên sau khi chọn 1 nhóm, hình ảnh các món ăn của mỗi nhóm sẽ được hiển thị và khi chọn món sẽ hiển thị chi tiết về món ăn cũng như giá tiền và 1 button để tăng giảm số lượng, 1 button để add món vào giỏ hàng. Đây là ảnh màn hình prototype về phần này các bạn xem có góp ý gì ko?
![food_details](https://user-images.githubusercontent.com/54387151/69008641-59c80a00-097f-11ea-8f59-5f916d3e4c34.png)

**Comment by kieth1205** [comment]
![image](https://user-images.githubusercontent.com/45708339/69008780-f343eb80-0980-11ea-965a-75d7e75f5532.png)
đây là layout mình tạo demo dựa trên hình ảnh của Thành

**Comment by Nguyenthinh19** [comment]
uhm vậy @itula và @mrbillyco99 xử lý phần này nhé. Có lỗi gì thì nhắn nhé.
