### ISSUE TITLE
Order food

### ISSUE THREAD

**Issue by Nguyenthinh19** [Nguyenthinh19/SE03-Group19#8]
App mình đã tạo xong các list món ăn. Giờ ta sẽ bàn đền phần Order food. Mọi người có ý kiến gì thì comment lại nhé

**Comment by mrbillyco99** [comment]
Ờ layout mà @kieth1205 đã tạo cho phần detail của mỗi món đã có một button để add món ăn đó vào giỏ hàng, t nghĩ giao diện của phần giỏ hàng nên có list các món ăn đã được add, giá tiền từng món, giá tiền tổng và 1 text field để khách hàng nhập địa chỉ. Mọi người có ý kiến gì thêm không?

**Comment by kieth1205** [comment]
Có nên đặt giới hạn số lượng của 1 món ăn không? Do nhà hàng tự chế biến món ăn và đảm bảo về chất lượng nên không thể làm với số lượng lớn được (trừ việc tổ chức tiệc, lúc đó người dùng sẽ liên hệ trước với nhà hàng để nhà hàng tổ chức công việc sau)

**Comment by itula** [comment]
t nghĩ trong phần order vẫn nên có thêm nút tăng giảm số lượng từng món ăn và có thêm 1 phần ghi chú để khách hàng có yêu cầu gì đặc biệt thì ghi vào thông báo với nhà hàng

**Comment by Nguyenthinh19** [comment]
@kieth1205 cái đấy cũng không quan trọng lắm, chắc ko cần

**Comment by Nguyenthinh19** [comment]
ok vậy t sẽ tạo thêm list các đơn hàng mà đã đặt thông qua nút đặt hành ở list food

**Comment by Nguyenthinh19** [comment]
phần này Thắng @kieth1205  xử lý nhé

**Comment by Nguyenthinh19** [comment]
Giao diện t nghĩ sẽ làm như list food thôi, tạo các cardview trong list , trong cardview sẽ có thông tin như @mrbillyco99 nhắn ở trên, gồm có tên món ăn, số lượng, giá tiền. Tạm thời là như vậy.
